In [10]:
# import numpy library

import numpy as np 

In [12]:
# Create a numpy array

a = np.array([0, 1, 2, 3, 4])
a

array([0, 1, 2, 3, 4])

In [14]:
# Print each element

print("a[0]:", a[0])
print("a[1]:", a[1])
print("a[2]:", a[2])
print("a[3]:", a[3])
print("a[4]:", a[4])

a[0]: 0
a[1]: 1
a[2]: 2
a[3]: 3
a[4]: 4


In [16]:
print(np.__version__)

1.26.4


In [18]:
# Check the type of the array

type(a)

numpy.ndarray

In [20]:
# Check the type of the values stored in numpy array

a.dtype

dtype('int64')

In [48]:
c = np.array([20, 1, 2, 3, 4])
c

array([20,  1,  2,  3,  4])

In [50]:
# Assign the first element to 100

c[0] = 100
c

array([100,   1,   2,   3,   4])

In [52]:
# Set the fourth element and fifth element to 300 and 400

c[3:5] = 300, 400
c

array([100,   1,   2, 300, 400])

In [54]:
# Slicing the numpy array

d = c[1:4]
d

array([  1,   2, 300])

In [56]:
# We can also define the steps in slicing, like this: [start:end:step].

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5:2])

[2 4]


In [58]:
print(arr[:4])

[1 2 3 4]


In [60]:
print(arr[4:])


[5 6 7]


In [62]:
print(arr[1:5:])

[2 3 4 5]


In [4]:
import numpy as np

In [6]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result = np.dot(matrix1, matrix2)
print(result)

[[19 22]
 [43 50]]


In [8]:
a=np.array([-1,1]) 
b=np.array([1,1]) 
np.dot(a,b) 

0

In [10]:
X=np.array([[1,0,1],[2,2,2]]) 
out=X[0:2,2]

In [14]:
X = np.array([[1,0],[0,1]])
Y = np.array([[2,2],[2,2]]) 
result = np.dot(X,Y)
print(result)

[[2 2]
 [2 2]]
